#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Title: Multi Image Parallel Mirror Flip Rotate
@author: @author: Giacomo Nodjoumi g.nodjoumi@jacobs-unversity.de

Script to mirror, flip and rotate given images

Created on Tue Aug 11 18:46:42 2020
@author: @author: Giacomo Nodjoumi g.nodjoumi@jacobs-unversity.de
"""


import os 
from datetime import datetime
import shutil
from PIL import Image, ImageOps
import pathlib
from tkinter import Tk,filedialog
from argparse import ArgumentParser

global PATH
global folder
global nh
global ixt
global ext

def answer(question):
    answ = None
    while answ not in ['yes','y','no','n']:
        print("Please enter yes/y or no/n.")
        answ = input(question+': ')
    return(answ)

def make_folder(name):
    os.getcwd()
    folder = name
    if os.path.exists(folder):
           qst = name + ' Folder exist, remove it? '
           answ = answer(qst)
           if answ in ['yes', 'y']:
               shutil.rmtree(folder)
               os.mkdir(folder)
               print(name, 'Folder created')
           else:
               now = datetime.now()
               folder = name +'_' + now.strftime("%d-%m-%Y_%H-%M-%S")
               print(folder, ' Folder not exist, creating.')
               os.mkdir(folder)
               print('Created new ', name,' Folder')
    else:
        print(name, ' Folder not exist, creating.')
        os.mkdir(folder)
        print('Created new ', name,' Folder')
    return(folder)

def get_paths(PATH, ixt):
    import glob
    os.chdir(PATH)
    filename = [i for i in glob.glob('**/*.'+ixt,recursive=True)]
    return(filename)




def transform(image):
    image_name= folder+'/'+pathlib.Path(image).name.split('.')[0]
    Image.MAX_IMAGE_PIXELS = None
    
    img = Image.open(image)

    im_flip = ImageOps.flip(img)
    im_flip.save(image_name+'_flipped.'+oxt)
    
    im_mir = ImageOps.mirror(img)
    im_mir.save(image_name+'_mirrored.'+oxt)
    
    im_rot90 = img.transpose(Image.ROTATE_90)
    im_rot90.save(image_name+'_rotated90.'+oxt)
    
    im_rot270 = img.transpose(Image.ROTATE_270)
    im_rot270.save(image_name+'_rotated270.'+oxt)
    
              
def parallel_resizer(files, JOBS):
    from joblib import Parallel, delayed
    Parallel (n_jobs=JOBS)(delayed(transform)(files[i])
                            for i in range(len(files)))

    

def chunk_creator(item_list, chunksize):
    import itertools
    it = iter(item_list)
    while True:
        chunk = tuple(itertools.islice(it, chunksize))
        if not chunk:
            break
        yield chunk


def main():
    image_list = get_paths(PATH, ixt)
    from tqdm import tqdm
    import psutil
    JOBS=psutil.cpu_count(logical=True)
    # JOBS = 2
    
    with tqdm(total=len(image_list),
             desc = 'Squaring images',
             unit='File') as pbar:
        
        filerange = len(image_list)
        chunksize = round(filerange/JOBS)
        if chunksize <1:
            chunksize=1
            JOBS = filerange
        chunks = []
        
                    
        for c in chunk_creator(image_list, JOBS):
            chunks.append(c)
    
        for i in range(len(chunks)):
            files = chunks[i]
            print('\nRendering: ', files)
            parallel_resizer(files, JOBS)
            pbar.update(JOBS)

if __name__ == "__main__":

    parser = ArgumentParser()
    parser.add_argument('--PATH', help='Directory with the files to be cropped')
    parser.add_argument('--m', help='Mirror the images')
    parser.add_argument('--f', help='Flip the images')
    parser.add_argument('--r', help='Rotate the images')
    parser.add_argument('--ixt', help='output file format (tiff,png,jpg')
    parser.add_argument('--oxt', help='output file format (tiff,png,jpg')
    args = parser.parse_args()  
    PATH = args.PATH
    m = args.m
    f = args.f
    r = args.r
    ixt = args.ixt
    oxt = args.oxt
    if PATH is None:
        root = Tk()
        root.withdraw()
        PATH = filedialog.askdirectory(parent=root,initialdir=os.getcwd(),title="Please select the folder with the files to be resized")
        print('Working folder:', PATH)
        
    if m is None:
        m = answer('Mirror all images? ')  
    if f is None:
        f = answer('Flip all images?' )
    if r is None:
        r = answer('Rotate all images of 90 and 270? ')
     
    if ixt is None:
        while ixt not in ['TIFF','tiff','PNG','png','JPG','jpg']:
         print('Please enter TIFF or tiff, PNG or png or JPG or jpg')    
         ixt = input('Enter input image format: ')
         
    if oxt is None:
        while oxt not in ['TIFF','tiff','PNG','png','JPG','jpg']:
            print('Please enter TIFF or tiff, PNG or png or JPG or jpg')    
            oxt = input('Enter output image format: ')
    
    
    os.chdir(PATH)

    folder = make_folder('transformed')
    
    
    main()